
CREATE TABLE users (
	id BIGINT NOT NULL AUTO_INCREMENT,
	full_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	is_email_verified BOOLEAN NOT NULL,
	email_verification_code VARCHAR(255)
);

CREATE TABLE projects (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);